### ISSUE TITLE
List of upcoming breaking changes

### ISSUE THREAD

**Issue by Nevon** [tulios/kafkajs#1013]
For many years now, we have never made a breaking change to KafkaJS (at least not intentionally), which is great for our users in the short term, but in the long term it also means we accumulate cruft and some slightly awkward APIs.

The intention of this issue is to collect all of the things that we have said we want to change in a single major version, so that when we feel that we have accumulated enough things we can actually put together a project to do them.

# Planned breaking changes

* [ ] Never commit from `consumer.seek` (#1012 #395)
* [ ] Remove `ResourceTypes` (#649)
* [ ] Remove `topic` argument from `admin.fetchOffsets` (#992)
* [ ] Remove `admin.getTopicMetadata` (#331)
* [ ] Remove `enforceRequestTimeout` and enable by default (#955)

Please leave a comment if you find more changes that should be on this list.

**Comment by ankon** [comment]
Remove typo-type: https://github.com/tulios/kafkajs/blob/addcd6f8bd1169b053fb633ee11c8cc3b9ae608e/types/index.d.ts#L729-L730

**Comment by t-d-d** [comment]
Switch default producer partitioner to ```JavaCompatiblePartitioner```.
I realise that changing this has issues as it would cause problems for users that upgrade kafkajs version for their current apps..  But as-is there are also issues when interacting with Java (or other) clients.  We actually recently got bitten by this in production after moving to a new Kafka cluster where topics had been mirrored across via MirrorMaker (i.e. the Java producer.)

One option could be to not have a default partitioner but require one to be specified.  Not a nice API but maybe it could be like that through the betas or for one dot version.

**Comment by Nevon** [comment]
Pushed a branch where I removed the `topic: string` argument from `consumer.subscribe`, which is replaced by `topics: string[]` but I'm waffling back and forth on whether or not it's a good change. The amount of complexity to support both is not that much, since we're pretty much just checking that we have one of the two arguments and then converting from `string` to `string[]` if needed.
