### ISSUE TITLE
Consumer "read_committed" isolation level

### ISSUE THREAD

**Issue by ianwsperber** [tulios/kafkajs#202]
To support transactions consumers should have an option to read only committed messages. In the Java API this is accomplished using the "isolation_level" option. The naive translation would be to provide an `isolationLevel` flag to our `consumer()` call.

**Tasks**
- [x] Pass the isolation level to fetch requests
- [x] Pass isolation level to ListOffsets to retrieve the LSO ("last stable offset") (blocked by #201)
- [x] Do not return aborted commits to the user

See the [Java implementation](https://github.com/apache/kafka/blob/044350f28e4d0edcc0503b2bc2593c0d25948ed0/clients/src/main/java/org/apache/kafka/clients/consumer/internals/Fetcher.java#L1184) for a reference on how to ignore aborted commits. Requires maintaining a map locally of aborted PIDs.

Along with #197 & #201 this should be all the work necessary for transactional consumers. @tulios LMK if this all sounds right to you.

**Comment by ianwsperber** [comment]
Our fetch implementation already defaults to the isolation level of read committed. This should continue to be the default behavior.

**Comment by ianwsperber** [comment]
Since we're going to default to "read_committed" behavior, we can hold off on providing a config option for isolation level until #210 (I'd mistakenly assumed to got "read_uncomitted" for free, but in practice the behavior we're getting is some weird mix of both)
