### ISSUE TITLE
Support committing offsets in transaction

### ISSUE THREAD

**Issue by ianwsperber** [tulios/kafkajs#207]
#### Overview

Kafka transactions provide support for the "consume-transform-produce loop" by allowing transactional producers to commit offsets for their recently consumed messages. This allows a client to ensure that offsets are committed for consumed messages _only_ if the transaction is committed.

The spec recommends we enable support by adding a method "sendOffsets" (`sendOffsetsToTransaction`) to the transactional producer.  This method will accept a data structure mapping topic-partitions to offsets, then perform the requests `AddOffsetsToTxnRequest` and subsequently `TxnOffsetCommit`.

Currently the consumer will automatically commit offsets when reading messages. We will need to update the API to allow users to _disable_ this option, so that they may send the offsets themselves via the producer's new `sendOffsetsToTransaction` method.

Would love to hear your thoughts on how best to update the consumer to accommodate this need @tulios @Nevon

#### Tasks

- [x] Add method `sendOffsetsToTransaction`
- [x] Update consumer to allow disabling auto committing
- [x] Keep offsetManager in sync with sent offsets

#### Links
- [consume-transform-produce loop](https://cwiki.apache.org/confluence/display/KAFKA/KIP-98+-+Exactly+Once+Delivery+and+Transactional+Messaging#KIP-98-ExactlyOnceDeliveryandTransactionalMessaging-4.Theconsume-transform-produceloop) (steps 4.3 & 4.4)
- [Java Implementation](https://github.com/apache/kafka/blob/d71cb54672e63d2f0f4b999668336642a9a63a1d/clients/src/main/java/org/apache/kafka/clients/producer/KafkaProducer.java#L673)

**Comment by tulios** [comment]
> We will need to update the API to allow users to disable this option, so that they may send the offsets themselves via the producer's new sendOffsetsToTransaction method

Right, the idea behind `eachMessage` was to provide a convenient and batteries included method to consume messages. Do you think users will decide to commit in different situations there? The way I see it `eachMessage` will call `AddOffsetsToTxnRequest` if it succeeds and `TxnOffsetCommit` once the batch is over or based on the `autoCommit` configurations.

`eachBatch` has the capabilities to disable some of the automation so it should be fine to have something like that there.

WDYT?
and since you already have the use case for a transactional producer it will be nice to have your view of the problem as well, which type of code would you like to have?

**Comment by sklose** [comment]
I like the idea of `eachMessage` providing this capability out of the box for simple use cases.

However I think it would be great if there was an option to disable that and use it similarly to the Java implementation. For instance I would like to use this feature in a message streaming framework that is designed run input/processing/output in their own async-chains so they can run concurrently in order to increase the throughput of a single instance of the service while keeping latencies low at the same time.

![image](https://user-images.githubusercontent.com/546088/48797345-e938cf80-eccf-11e8-9aac-92534390eb50.png)

One input message can result in many output messages and I would need to a) encapsulate the output messages in a transaction for atomicity reasons and b) commit the offset of the corresponding input message to guarantee EOS

**Comment by tulios** [comment]
Ok, I think I understand now, you want to commit the message before you process it, right? What about passing a `commitTransaction` or `addOffsetToTransaction` to the `eachMessage` callback? Without the need of passing the offset to the function.

**Comment by sklose** [comment]
maybe let me try to describe it in pseudo code:

```typescript
let inputQueue = new Queue(maxCapacity); // will block when capacity is reached
let outputQueue = new Queue(maxCapacity);

// input "thread"
(async () => {
await consumer.run({
  eachBatch: async ({ batch, resolveOffset, heartbeat, isRunning }) => {
    for (let message of batch.messages) {
      await inputQueue.push({
        topic: batch.topic,
        partition: batch.partition,
        offset: batch.offset,
        key: message.key.toString(),
        value: message.value.toString(),
      })

      await heartbeat()
    }
  },
})
})();

// processing "thread"
(async () => {
  for await (item of inputQueue) {
    await outputQueue.push({
        topic: "output-topic",
        key: "output msg 1",
        value: "hello",
        fromInput: item // add this as reference
      });
    await outputQueue.push({
        topic: "output-topic",
        key: "output msg 2",
        value: "world",
        fromInput: item
      });
  }
})();

// output "thread"
(async () => {
  for await (const batch of outputQueue) {
    publisher.startTx();
    publisher.addOffsetToTx(batch.determineHighestInputOffset());
    for (const msg of batch) {
      publisher.addMsgToTx(msg);
    }
    publisher.commitTx();
  }
})();
```

The input "thread" is reading in msgs as fast as possible from kafka and putting them in the input queue so they are readily available to be processed (effectively a prefetching mechanism to avoid broker roundtrip latencies).

The processing "thread" will run the input -> output transformation function based on data available in the input queue (this effectively happens while node is waiting for the async I/O from either the input prefetching or the output publishing).

The publishing "thread" will publish all the generated outputs in large batches to kafka (the batches accumulate in between I/O while the processing "thread" is running - the bigger the batch, the more time for processing inputs and the bigger the next batch -> higher throughput). So the committed offset I want to attach to my output transaction is the one of the input message that generated the output - that message might have come from a previous run on `eachBatch` though.

Hope this makes it a little more clear what I am trying to do :-) This design loosely mimics the disrupter design pattern in case you are familiar with that (https://martinfowler.com/articles/lmax.html)

**Comment by ianwsperber** [comment]
I'm going to begin by doing some exploratory work on this so I can better understand how we can/cannot achieve this functionality within the existing API. @tulios let me know if you have further thoughts/feedback in the meanwhile on how to implement `sendOffsets`.

**Comment by ianwsperber** [comment]
@tulios @Nevon Working through the implementation & thinking about the problem I really don't see a way of accomplishing this without being able to disable committing of offsets within the consumer's processing method (eg `eachBatch`).

As @sklose's example illustrates, the each step in the `consume-transform-produce` loop is independent of the others. We may consume many messages, then transform those messages at an arbitrary later point in time, then produce those messages at yet another arbitrary later date. It's not sufficient to perform the transform/produce step within the eachBatch callback, in this model we need to be able to independently call a commit method (in this case `sendOffsets`) at an arbitrary later date.

My proposal would be to allow disabling auto committing for `eachBatch`, then provide a mechanism within `eachBatch` to get the current set of (resolved?) offsets. This data structure representing the offsets could then be passed to either `consume.commitOffsets()` (non-transactional) or `producer.sendOffsets()` (transactional). We would enable this only for `eachBatch` and preserve the "batteries included" methodology of the `eachMessage` method. In my mind this is less confusing & more explicit than trying to fit this use case into the existing `each` paradigm.

Thoughts?

**Comment by tulios** [comment]
@ianwsperber that was also my proposal, go for it!

**Comment by Nevon** [comment]
Closing this as per #232
